# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_check_dialog(object):
    def setupUi(self, check_dialog):
        check_dialog.setObjectName("check_dialog")
        check_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        check_dialog.resize(400, 100)
        check_dialog.setMinimumSize(QtCore.QSize(400, 100))
        check_dialog.setMaximumSize(QtCore.QSize(400, 100))
        self.centralwidget = QtWidgets.QWidget(check_dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(50, 50, 141, 41))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_no = QtWidgets.QPushButton(self.centralwidget)
        self.btn_no.setGeometry(QtCore.QRect(210, 50, 141, 41))
        self.btn_no.setObjectName("btn_no")
        check_dialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(check_dialog)
        QtCore.QMetaObject.connectSlotsByName(check_dialog)

    def retranslateUi(self, check_dialog):
        _translate = QtCore.QCoreApplication.translate
        check_dialog.setWindowTitle(_translate("check_dialog", "Удаление"))
        self.label.setText(_translate("check_dialog", "Вы действительно хотите удалить запись?"))
        self.btn_ok.setText(_translate("check_dialog", "Да"))
        self.btn_no.setText(_translate("check_dialog", "Отмена"))
