# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error_edit(object):
    def setupUi(self, error_edit):
        error_edit.setObjectName("error_edit")
        error_edit.setWindowModality(QtCore.Qt.ApplicationModal)
        error_edit.resize(269, 77)
        self.centralwidget = QtWidgets.QWidget(error_edit)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_error = QtWidgets.QPushButton(self.centralwidget)
        self.btn_error.setGeometry(QtCore.QRect(90, 40, 75, 23))
        self.btn_error.setObjectName("btn_error")
        error_edit.setCentralWidget(self.centralwidget)

        self.retranslateUi(error_edit)
        QtCore.QMetaObject.connectSlotsByName(error_edit)

    def retranslateUi(self, error_edit):
        _translate = QtCore.QCoreApplication.translate
        error_edit.setWindowTitle(_translate("error_edit", "Ошибка"))
        self.label.setText(_translate("error_edit", "Необходимо выбрать запись"))
        self.btn_error.setText(_translate("error_edit", "ОК"))
