# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 550)
        MainWindow.setMinimumSize(QtCore.QSize(400, 550))
        MainWindow.setMaximumSize(QtCore.QSize(400, 550))
        MainWindow.setStyleSheet("background-color:rgb(115, 183, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 181, 161))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../img/login.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.login_input = QtWidgets.QLineEdit(self.centralwidget)
        self.login_input.setGeometry(QtCore.QRect(30, 240, 340, 60))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.login_input.setFont(font)
        self.login_input.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border: 3px solid  rgb(47, 85, 255);\n"
"border-radius: 30px;\n"
"color: rgb(47, 85, 255);\n"
"")
        self.login_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.login_input.setAlignment(QtCore.Qt.AlignCenter)
        self.login_input.setObjectName("login_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 310, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_chek_auth = QtWidgets.QPushButton(self.centralwidget)
        self.btn_chek_auth.setGeometry(QtCore.QRect(120, 430, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_chek_auth.setFont(font)
        self.btn_chek_auth.setStyleSheet("QPushButton {\n"
"    background-color: rgb(47, 85, 255);\n"
"    border-radius: 30px;\n"
"    border: 1px solid #fff;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    background-color: rgb(30, 55, 167);\n"
"}")
        self.btn_chek_auth.setObjectName("btn_chek_auth")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(30, 360, 340, 60))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border: 3px solid  rgb(47, 85, 255);\n"
"border-radius: 30px;\n"
"color: rgb(47, 85, 255);\n"
"")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setAlignment(QtCore.Qt.AlignCenter)
        self.password_input.setObjectName("password_input")
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(40, 500, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color: rgb(255, 0, 4);")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "ЛОГИН"))
        self.label_3.setText(_translate("MainWindow", "ПАРОЛЬ"))
        self.btn_chek_auth.setText(_translate("MainWindow", "ВОЙТИ"))
