# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_wid.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setStyleSheet("background-color: rgb(203, 233, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_books = QtWidgets.QPushButton(self.centralwidget)
        self.btn_books.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_books.setFont(font)
        self.btn_books.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_books.setStyleSheet("background-color: rgb(158, 205, 255);\n"
"border: 1px solid rgb(141, 184, 227);\n"
"border-radius: 5;")
        self.btn_books.setObjectName("btn_books")
        self.verticalLayout.addWidget(self.btn_books)
        self.btn_journal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_journal.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_journal.setFont(font)
        self.btn_journal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_journal.setStyleSheet("background-color: rgb(158, 205, 255);\n"
"border: 1px solid rgb(141, 184, 227);\n"
"border-radius: 5;")
        self.btn_journal.setObjectName("btn_journal")
        self.verticalLayout.addWidget(self.btn_journal)
        self.btn_clients = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clients.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clients.setFont(font)
        self.btn_clients.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clients.setStyleSheet("background-color: rgb(158, 205, 255);\n"
"border: 1px solid rgb(141, 184, 227);\n"
"border-radius: 5;")
        self.btn_clients.setObjectName("btn_clients")
        self.verticalLayout.addWidget(self.btn_clients)
        self.btn_author = QtWidgets.QPushButton(self.centralwidget)
        self.btn_author.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_author.setFont(font)
        self.btn_author.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_author.setStyleSheet("background-color: rgb(158, 205, 255);\n"
"border: 1px solid rgb(141, 184, 227);\n"
"border-radius: 5;")
        self.btn_author.setObjectName("btn_author")
        self.verticalLayout.addWidget(self.btn_author)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_search = QtWidgets.QLineEdit(self.centralwidget)
        self.input_search.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 24px;")
        self.input_search.setObjectName("input_search")
        self.horizontalLayout_3.addWidget(self.input_search)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("background-color: rgb(158, 205, 255);\n"
"border: 1px solid rgb(141, 184, 227);\n"
"border-radius: 5;")
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_3.addWidget(self.btn_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.main_table = QtWidgets.QTableWidget(self.centralwidget)
        self.main_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 24px;\n"
"QTableWidget::focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.main_table.setObjectName("main_table")
        self.main_table.setColumnCount(0)
        self.main_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.main_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("background-color: rgb(158, 205, 255);\n"
"border: 1px solid rgb(141, 184, 227);\n"
"border-radius: 5;")
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_2.addWidget(self.btn_add)
        self.btn_edit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_edit.setFont(font)
        self.btn_edit.setStyleSheet("background-color: rgb(158, 205, 255);\n"
"border: 1px solid rgb(141, 184, 227);\n"
"border-radius: 5;")
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout_2.addWidget(self.btn_edit)
        self.btn_del = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_del.setFont(font)
        self.btn_del.setStyleSheet("background-color: rgb(158, 205, 255);\n"
"border: 1px solid rgb(141, 184, 227);\n"
"border-radius: 5;")
        self.btn_del.setObjectName("btn_del")
        self.horizontalLayout_2.addWidget(self.btn_del)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_books.setText(_translate("MainWindow", "Книги"))
        self.btn_journal.setText(_translate("MainWindow", "Журнал выдачи"))
        self.btn_clients.setText(_translate("MainWindow", "Клиенты"))
        self.btn_author.setText(_translate("MainWindow", "Авторы"))
        self.btn_search.setText(_translate("MainWindow", "Поиск"))
        self.btn_add.setText(_translate("MainWindow", "Добавить"))
        self.btn_edit.setText(_translate("MainWindow", "Изменить"))
        self.btn_del.setText(_translate("MainWindow", "Удалить"))
