# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_author(object):
    def setupUi(self, new_author):
        new_author.setObjectName("new_author")
        new_author.setWindowModality(QtCore.Qt.ApplicationModal)
        new_author.resize(575, 172)
        self.centralwidget = QtWidgets.QWidget(new_author)
        self.centralwidget.setObjectName("centralwidget")
        self.name_auth = QtWidgets.QLineEdit(self.centralwidget)
        self.name_auth.setGeometry(QtCore.QRect(20, 10, 531, 41))
        self.name_auth.setObjectName("name_auth")
        self.btn_ok_auth = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok_auth.setGeometry(QtCore.QRect(90, 70, 171, 41))
        self.btn_ok_auth.setObjectName("btn_ok_auth")
        self.btn_canc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_canc.setGeometry(QtCore.QRect(310, 70, 171, 41))
        self.btn_canc.setObjectName("btn_canc")
        new_author.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(new_author)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 26))
        self.menubar.setObjectName("menubar")
        new_author.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(new_author)
        self.statusbar.setObjectName("statusbar")
        new_author.setStatusBar(self.statusbar)

        self.retranslateUi(new_author)
        QtCore.QMetaObject.connectSlotsByName(new_author)

    def retranslateUi(self, new_author):
        _translate = QtCore.QCoreApplication.translate
        new_author.setWindowTitle(_translate("new_author", "Новый автор"))
        self.btn_ok_auth.setText(_translate("new_author", "Добавить"))
        self.btn_canc.setText(_translate("new_author", "Отмена"))
